### PR TITLE
Ignore images folder

### PR DESCRIPTION
**Pull request by brunowego**
:+1:

### CODE REVIEW

**Comment by Bockit** [comment]
Hi @brunowego 

The `images/` folder can and should be added, but `npm-debug.log` shouldn't be committed to the repo so that should be kept in `.gitignore`.

**Comment by brunowego** [comment]
The `npm-debug.log` only will be created if your env have a error. Not common have this file in `.gitignore` file.

**Comment by Bockit** [comment]
Yep. But it does get generated sometimes and we don't want it to be committed if it's there :)

**Comment by brunowego** [comment]
Okay, okay, you win! :+1:

**Comment by Bockit** [comment]
Thanks for the pull request!

**Pull request merged**
